function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Teacher Tools')
    .addItem('Open Demographics', 'openStudentDemographics')
    .addItem('Save SCC Call Entry', 'saveSccToRoster')
    .addItem('Reset SCC Call Entry', 'resetCallEntry')
    .addItem('Log Selected SCC/Attempt in PowerSchool', 'logSccInPowerSchool')
    .addSeparator()
    .addItem('Refresh Student Data', 'refreshStudentDataAndCounselors')
    .addSeparator()
    .addItem('Log Ready ECC Rows', 'logReadyEccRows')
    .addItem('Log Current ECC Row & Open PowerSchool', 'logCurrentEccRowAndOpenPowerSchool')
    .addItem('Set Up / Repair ECC Batch Columns', 'setupEccBatchLayout')
    .addSeparator()
    .addItem('Prepare ECC Reminder Emails', 'prepareEccReminderEmails')
    .addItem('Prepare ECC Reschedule Emails', 'prepareEccRescheduleEmails')
    .addItem('Record ECC Email Receipts', 'showEccEmailReceiptDialog')
    .addSeparator()
    .addItem('Update Engageli Attendance', 'updateEngageliAttendance')
    .addItem('Set Up / Repair Attendance Settings', 'setupEngageliAttendanceSettings')
    .addSeparator()
    .addItem('Save WIG Snapshot', 'saveWigSnapshot')
    .addItem('Enable Tuesday WIG Snapshots', 'enableTuesdayWigSnapshots')
    .addToUi();
}
